# Generated by Django 4.1 on 2022-08-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('amount', models.IntegerField()),
                ('desc', models.TextField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
